name 'lab_base'
maintainer 'James Massardo'
maintainer_email 'james@dxrf.com'
license 'All Rights Reserved'
description 'Installs/Configures lab_base'
long_description 'Installs/Configures lab_base'
version '0.1.2'
chef_version '>= 13.0'
supports 'ubuntu'
depends 'chef-client'
depends 'audit'
depends 'cis-baseline'
issues_url 'https://github.com/jmassardo/lab_base/issues'
source_url 'https://github.com/jmassardo/lab_base'
